apiVersion: v1
kind: Service
metadata:
  name: product-order-api
spec:
  selector:
    app: product-order-api
  ports:
    - protocol: "TCP"
      port: 9090 # The port that the service is running on in the cluster
      targetPort: 9090 # The port exposed by the service
  type: NodePort # type of the service.